version: '3.8'

services:
  redis:
    image: redis:5.0.0
    container_name: master
    ports:
      - "6379:6379"
    networks:
      - redis-replication

  redis-slave:
    image: redis:5.0.0
    container_name: slave
    ports:
      - "6380:6379"
    command: redis-server --slaveof master 6379
    depends_on:
      - redis
    networks:
      - redis-replication

  redis-cli:
    image: redis:5.0.0
    container_name: cli
    networks:
      - redis-replication

networks:
  redis-replication:
    driver: bridge